### From elastic cloud to on-premise
POST https://elasticcloud:9243/_reindex
Content-Type: application/json

{
  "source": {
    "remote": {
      "host": "http://remote-elasticsearch:9200",
      "username": "user",
      "password": "pass"
    },
    "index": "index-YYYYMMdd",
    "query": {
      "match_all": {}
    }
  },
  "dest": {
    "index": "index-YYYYMMdd"
  }
}

### From on-premise to elastic cloud
POST http://remote-elasticsearch:9200/_reindex
Content-Type: application/json

{
  "source": {
    "remote": {
      "host": "https://elasticcloud:9243",
      "username": "user",
      "password": "pass"
    },
    "index": "index-YYYYMMdd",
    "query": {
      "match_all": {}
    }
  },
  "dest": {
    "index": "index-YYYYMMdd"
  }
}


# The host parameter must contain a scheme, host, port (e.g. https://otherhost:9200) and optional
# path (e.g. https://otherhost:9200/proxy). The username and password parameters are optional,
# and when they are present _reindex will connect to the remote Elasticsearch node using basic auth.
# Be sure to use https when using basic auth or the password will be sent in plain text.
#
# Remote hosts have to be explicitly whitelisted in elasticsearch.yaml using the reindex.remote.whitelist property.
# It can be set to a comma delimited list of allowed remote host and port combinations
# (e.g. otherhost:9200, another:9200, 127.0.10.*:9200, localhost:*). Scheme is ignored by the whitelist -
# only host and port are used, for example: reindex.remote.whitelist:
# "otherhost:9200, another:9200, 127.0.10.*:9200, localhost:*"
#
# The whitelist must be configured on any nodes that will coordinate the reindex.
#
# This feature should work with remote clusters of any version of Elasticsearch you are likely to find.
# This should allow you to upgrade from any version of Elasticsearch to the current version by reindexing
# from a cluster of the old version.
#
# To enable queries sent to older versions of Elasticsearch the query parameter is sent directly to
# the remote host without validation or modification.
